### PR TITLE
Correct Sonoff TRVZB local temperature calibration min/max

### PR DESCRIPTION
**Pull request by fgsch**
From https://github.com/Koenkk/zigbee-herdsman-converters/pull/8214 via https://github.com/zigpy/zha-device-handlers/pull/3358#issuecomment-2485862165.

### CODE REVIEW

**Comment by tr4nt0r** [comment]
I think the step should also be 0.1

**Comment by fgsch** [comment]
@tr4nt0r, can you elaborate on why you think so? The original change uses 0.2.

**Comment by tr4nt0r** [comment]
I can write to the `local_temperature_calibration` attribute directly and it takes any integer value without any problems. Also how would it otherwise be possible to set a value of +12.7

**Comment by fgsch** [comment]
The max and min don't necessarily imply those are the values you can use; they correspond to the range for this type -128..127 (int8) before applying the multiplier.

**Comment by TheJulianJES** [comment]
I think we could increase the step size if we wanted. I'd guess 0.2 was originally chosen, as it's easier doing 0.2°C steps when moving the slider in the HA frontend.

I'll merge this for now, as Z2M also uses step size 0.2 Feel free to open a separate PR if you'd prefer the smaller step size.
Does HA also limit the values to the step size when entered manually?

**Review by TheJulianJES — APPROVED** [review]
Thanks!

**Comment by tr4nt0r** [comment]
> I think we could increase the step size if we wanted. I'd guess 0.2 was originally chosen, as it's easier doing 0.2°C steps when moving the slider in the HA frontend.
> 
> I'll merge this for now, as Z2M also uses step size 0.2 Feel free to open a separate PR if you'd prefer the smaller step size. Does HA also limit the values to the step size when entered manually?

@TheJulianJES if the number entity is used, Home Assistant validates the inputs and allows only the values within min/max and I think it also the step is validated, but I'm not 100% sure about that right now. Currently the entity for the offset has a step of 0.1 so it would change with the update. Having a step of 0.1 would make it easier when calculating the offsets via automation.

**Comment by TheJulianJES** [comment]
> Currently the entity for the offset has a step of 0.1 

Ah, the ZCL entity indeed has a 0.1 step. I've only looked at the Sonoff one before. We should probably change this one then.

**Comment by fgsch** [comment]
@TheJulianJES Ok, if a 0.1 step is the norm, I can open a PR to do this.

**Comment by TheJulianJES** [comment]
See:
- https://github.com/zigpy/zha/pull/304
- https://github.com/zigpy/zha/pull/306

**Pull request merged**
