### PR TITLE
Rename update to async_update for consistency

### PR DESCRIPTION
**Pull request by dmulcahey**
SSIA

### CODE REVIEW

**Comment by puddly** [comment]
Does this need any changes in Core?

**Comment by dmulcahey** [comment]
> Does this need any changes in Core?

I still have to look but I don’t think so.

**Review by TheJulianJES — APPROVED** [review]
Shouldn't need any changes in core: [homeassistant/components/zha/entity.py#L137-L141](https://github.com/home-assistant/core/blob/162b734be756d48e5e36ec828e6703110b7e2f59/homeassistant/components/zha/entity.py#L137-L141)
(and don't see `update()` being called anywhere else either)

**Comment by dmulcahey** [comment]
> Shouldn't need any changes in core: [homeassistant/components/zha/entity.py#L137-L141](https://github.com/home-assistant/core/blob/162b734be756d48e5e36ec828e6703110b7e2f59/homeassistant/components/zha/entity.py#L137-L141) (and don't see `update()` being called anywhere else either)

thx. I just double checked as well and I agree. 

image

**Pull request merged**
